[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
EasyHybrid = "61bb816a-e6af-4913-ab9e-91bff2e122e3"
Hyperopt = "93e5fe13-2215-51db-baaf-2e9a34fb2712"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"

[sources]
EasyHybrid = {path = ".."}

[compat]
Documenter = "1"
DocumenterVitepress = "0.3"
